#!/system/bin/sh

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PACKAGE_NAME=me.zhanghai.android.beeshell
class_path="$(pm path "${PACKAGE_NAME}")"
class_path="${class_path#package:}"
sdk_version="$(getprop ro.build.version.sdk)"
if [ "$sdk_version" -gt "28" ]; then
  java_options=" -XjdwpProvider:adbconnection"
elif [ "$sdk_version" -eq "28" ]; then
  java_options=" -XjdwpProvider:adbconnection -XjdwpOptions:suspend=n,server=y -Xcompiler-option --debuggable"
else
  java_options=" -Xrunjdwp:transport=dt_android_adb,suspend=n,server=y -Xcompiler-option --debuggable"
fi
CLASSPATH="${class_path}" /system/bin/app_process${java_options} /system/bin --nice-name="${PACKAGE_NAME}:shell" "${PACKAGE_NAME}.ShellMain" "$@"
